permalink: /:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path: /atom.xml

production_url : http://blog.antrob.us
title : James Antrobus

author :
  name : James Antrobus
  email : james@antrob.us
  github : jamesantrobus
  twitter : james_antrobus
  feedbuder : feedname

exclude: .rbenv-version
